language: elixir
elixir:
  - 1.2.2
  - 1.3.0
before_script:
  - mix ecto.setup
services:
  - postgresql
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
