language: elixir
elixir:
  - 1.2.2
  - 1.3.0
before_script:
  - npm install -g brunch
  - npm install
  - brunch build --production
  - MIX_ENV=test mix do deps.get, deps.compile, ecto.setup, phoenix.digest
  - git config --global user.email "travisci@opie.at"
  - git config --global user.name  "Travis CI"
  - git add priv @@ git commit -m 'Build static assets for Heroku'
services:
- postgresql
after_script:
- mix deps.get --only docs
- MIX_ENV=docs mix inch.report
- MIX_ENV=test mix coveralls.travis
deploy:
  provider: heroku
  app: safe-forest-49166
  buildpack: https://github.com/HashNuke/heroku-buildpack-elixir.git
  api_key:
    secure: SzltmJzAUJY/BrEDrbSiGW8FpwJX8/TL0XwNK5x2/O/sl6EyZEL48FXQMhiUom3nWsPo6FqmU+Jtv1GyD7BGONmI35rzdNJDHOUy1yR7xDV0t9tjO4NY0o0LAhSCruZU4oEmMCnq64NHfRZqKZBIMxHZQEmiXP/alggsOi4hM2px1faBUDRTBiq2lRW9111fewHB/uBBHI4QdPdYlqf+uenhwFl4UXTSn55qUqRtyhfV9uCG5welnJmXrLOaNKEjfGo6elaehHChkTMKPhQzIV0xOEh8eA17Ckk44OJDD+9F/638T7h3eFy8BwNd7bdaConToTyUKo+RQTGORE6/ckMDEpUGYYuIjZNs/PaCTHRuJrk4IrCpZ3Wk5Hv88UVylEATPGpM7ca/5Uq4tAa0Su+CcfqCfD38oGzNUuhHNeR/5NU53acPxwD+bcoQEh3LDWBLRsVUGL1m8ZU66GNieMHjkYHvVjpm/J0uew7yJqamLj6BdwQCAUWZwxOV8gCMvL1Sy9RHKoNAxLgm+7D8d6r41XVOs7tL+0axeY3D6VraI8OrQWm8yHasZKV0522iNiiklU9sy4UZXM8TfcHj7yM+CBhXnTx0yjmqHZy8ZyP1JdfQ3msA8HBk18Lp1/eeGTrvBk80Op18CBL457wlsRuSt1JOiXQuzNG3k5850xc=
after_deploy:
  - heroku run "mix ecto.migrate" -a safe-forest-49166
